# 开发环境配置
server:
  # 服务端口
  port: 80

dubbo:
  application:
    id: springboot-dubbo-test
    name: springboot-dubbo-privider
  registry:
    id: myProject
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    serialization: hessian2
  scan:
    base-packages: cn.mr


